@echo off
REM ============================================================================
REM DagTech Miner - Windows Installer
REM Copyright (c) 2024-2026 DagTech Ltd / Dawie Nel
REM https://dagtech.network
REM ============================================================================
setlocal enabledelayedexpansion

set "DAGTECH_VERSION=1.0.0"
set "INSTALL_DIR=%USERPROFILE%\.dagtech-miner"
set "CONFIG_FILE=%INSTALL_DIR%\config.env"
set "BIN_DIR=%INSTALL_DIR%\bin"
set "DASHBOARD_DIR=%INSTALL_DIR%\dashboard"
set "LOG_DIR=%INSTALL_DIR%\logs"

echo.
echo   =============================================
echo     DagTech Miner v%DAGTECH_VERSION% - Windows Installer
echo     dagtech.network
echo     By Dawie Nel / DagTech Ltd
echo   =============================================
echo.

REM ---- Check Windows version ----
echo [DagTech] Checking system...
ver | findstr /i "10\. 11\." >nul 2>&1
if errorlevel 1 (
    echo [DagTech] WARNING: Recommended Windows 10 or newer
)

REM ---- Check CPU ----
echo [DagTech] Detecting hardware...
for /f "tokens=2 delims==" %%a in ('wmic cpu get NumberOfLogicalProcessors /value 2^>nul ^| find "="') do set "CPU_CORES=%%a"
for /f "tokens=2 delims==" %%a in ('wmic cpu get Name /value 2^>nul ^| find "="') do set "CPU_NAME=%%a"
for /f "tokens=2 delims==" %%a in ('wmic os get TotalVisibleMemorySize /value 2^>nul ^| find "="') do set /a "RAM_MB=%%a / 1024"

echo.
echo   Hardware Summary:
echo   CPU:     %CPU_NAME%
echo   Cores:   %CPU_CORES%
echo   RAM:     %RAM_MB% MB
echo.

REM ---- Check minimum requirements ----
if %RAM_MB% LSS 512 (
    echo [DagTech] ERROR: Insufficient RAM. Minimum 512MB required.
    pause
    exit /b 1
)

REM ---- Check for GPU ----
set "GPU_AVAILABLE=0"
nvidia-smi >nul 2>&1
if not errorlevel 1 (
    set "GPU_AVAILABLE=1"
    echo [DagTech] NVIDIA GPU detected
    for /f "tokens=*" %%a in ('nvidia-smi --query-gpu^=name --format^=csv^,noheader 2^>nul') do echo   GPU: %%a
)

REM ---- Check for compiler ----
echo.
echo [DagTech] Checking build tools...
set "HAS_GCC=0"
set "HAS_MSVC=0"
where gcc >nul 2>&1
if not errorlevel 1 set "HAS_GCC=1"
where cl >nul 2>&1
if not errorlevel 1 set "HAS_MSVC=1"

if "%HAS_GCC%"=="0" if "%HAS_MSVC%"=="0" (
    echo [DagTech] No C compiler found - downloading pre-built binary...
    if not exist "%BIN_DIR%" mkdir "%BIN_DIR%"
    powershell -Command "Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/Dagtechltd/dagtech-miner/main/bin/windows/dagtech-miner.exe' -OutFile '%BIN_DIR%\dagtech-miner.exe'"
    if exist "%BIN_DIR%\dagtech-miner.exe" (
        echo [DagTech] Pre-built binary downloaded successfully
        set "SKIP_BUILD=1"
    ) else (
        echo [DagTech] Download failed. Please install MinGW-w64 manually:
        echo           https://www.mingw-w64.org/downloads/
        pause
        exit /b 1
    )
)
if not defined SKIP_BUILD echo [DagTech] Compiler found

REM ---- Configuration ----
echo.
echo   --- Configuration ---
echo.

:wallet_prompt
set /p "WALLET=  Enter wallet address (0x...): "
    powershell -Command "if ('%WALLET%' -match '^0x[0-9a-fA-F]{40}$') { exit 0 } else { exit 1 }"
if errorlevel 1 (
    echo [DagTech] Invalid wallet format. Must start with 0x
    goto :wallet_prompt
)

echo.
echo   Mining mode:
if "%GPU_AVAILABLE%"=="1" (
    echo     1^) CPU only
    echo     2^) GPU only
    echo     3^) CPU + GPU [recommended]
    echo.
    set /p "MODE_CHOICE=  Choice [1-3]: "
) else (
    echo     1^) CPU only ^(no GPU detected^)
    set "MODE_CHOICE=1"
)

set "MINING_MODE=cpu"
if "%MODE_CHOICE%"=="2" set "MINING_MODE=gpu"
if "%MODE_CHOICE%"=="3" set "MINING_MODE=both"
echo [DagTech] Mode: %MINING_MODE%

REM ---- Thread count ----
set /a "DEFAULT_THREADS=%CPU_CORES% / 2"
if %DEFAULT_THREADS% LSS 1 set "DEFAULT_THREADS=1"
echo.
set /p "THREADS=  CPU threads (1-%CPU_CORES%, default %DEFAULT_THREADS%): "
if "%THREADS%"=="" set "THREADS=%DEFAULT_THREADS%"

REM ---- Pool ----
echo.
set "POOL_HOST=excalibur.dagtech.network"
set "POOL_PORT=3334"
set /p "POOL_INPUT=  Pool address (default: %POOL_HOST%): "
if not "%POOL_INPUT%"=="" set "POOL_HOST=%POOL_INPUT%"
set /p "PORT_INPUT=  Pool port (default: %POOL_PORT%): "
if not "%PORT_INPUT%"=="" set "POOL_PORT=%PORT_INPUT%"

REM ---- Worker name ----
echo.
set "WORKER=dagtech"
set /p "WORKER_INPUT=  Worker name (default: dagtech): "
if not "%WORKER_INPUT%"=="" set "WORKER=%WORKER_INPUT%"

echo.
echo [DagTech] Configuration complete

REM ---- Create directories ----
echo [DagTech] Creating installation directories...
if not exist "%INSTALL_DIR%" mkdir "%INSTALL_DIR%"
if not exist "%BIN_DIR%" mkdir "%BIN_DIR%"
if not exist "%DASHBOARD_DIR%" mkdir "%DASHBOARD_DIR%"
if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"

REM ---- Save config ----
(
echo # DagTech Miner Configuration
echo # Generated by DagTech Installer v%DAGTECH_VERSION%
echo WALLET=%WALLET%
echo POOL_HOST=%POOL_HOST%
echo POOL_PORT=%POOL_PORT%
echo MINING_MODE=%MINING_MODE%
echo THREADS=%THREADS%
echo WORKER_NAME=%WORKER%
echo METRICS_PORT=8880
) > "%CONFIG_FILE%"
echo [DagTech] Config saved

REM ---- Build ----
if defined SKIP_BUILD (
    echo [DagTech] Using pre-built binary - skipping compile
) else (
    echo [DagTech] Building DagTech Miner...
    set "SRC_DIR=%~dp0src"
    if not exist "%SRC_DIR%\dagtech_miner.c" (
        echo [DagTech] Source not found locally, downloading from GitHub...
        set "TMP_SRC=%TEMP%\dagtech-miner-src"
        if exist "%TMP_SRC%" rmdir /s /q "%TMP_SRC%"
        git clone --depth 1 https://github.com/Dagtechltd/dagtech-miner.git "%TMP_SRC%" >nul 2>&1
        if errorlevel 1 (
            echo [DagTech] Git clone failed, trying PowerShell download...
            mkdir "%TMP_SRC%\src" 2>nul
            powershell -Command "Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/Dagtechltd/dagtech-miner/main/src/dagtech_miner.c' -OutFile '%TMP_SRC%\src\dagtech_miner.c'" 2>nul
            if not exist "%TMP_SRC%\src\dagtech_miner.c" (
                echo [DagTech] ERROR: Could not download source. Check internet connection.
                pause
                exit /b 1
            )
            powershell -Command "Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/Dagtechltd/dagtech-miner/main/src/dagtech_sha256.h' -OutFile '%TMP_SRC%\src\dagtech_sha256.h'" 2>nul
        )
        set "SRC_DIR=!TMP_SRC!\src"
        if exist "%~dp0dashboard\index.html" (
            REM keep local dashboard
        ) else if exist "!TMP_SRC!\dashboard\index.html" (
            copy /y "!TMP_SRC!\dashboard\index.html" "%DASHBOARD_DIR%\" >nul
        )
    )
    if not exist "!SRC_DIR!\dagtech_miner.c" (
        echo [DagTech] ERROR: Source not found after download attempt.
        pause
        exit /b 1
    )
    if "%HAS_GCC%"=="1" (
        gcc -O2 -Wall -o "%BIN_DIR%\dagtech-miner.exe" "%SRC_DIR%\dagtech_miner.c" -lws2_32 -lpthread
    ) else (
        cl /O2 /Fe:"%BIN_DIR%\dagtech-miner.exe" "%SRC_DIR%\dagtech_miner.c" ws2_32.lib
    )
    if errorlevel 1 (
        echo [DagTech] BUILD FAILED
        pause
        exit /b 1
    )
    echo [DagTech] Build successful
)

REM ---- Copy dashboard ----
echo [DagTech] Installing dashboard...
if exist "%~dp0dashboard\index.html" (
    copy /y "%~dp0dashboard\index.html" "%DASHBOARD_DIR%\" >nul
)

REM ---- Create launcher batch files ----
echo [DagTech] Creating launcher scripts...

(
echo @echo off
echo REM DagTech Miner Launcher - dagtech.network
echo setlocal
echo set "CONFIG=%USERPROFILE%\.dagtech-miner\config.env"
echo set "BIN=%USERPROFILE%\.dagtech-miner\bin\dagtech-miner.exe"
echo set "LOG_DIR=%USERPROFILE%\.dagtech-miner\logs"
echo set "DASHBOARD=%USERPROFILE%\.dagtech-miner\dashboard"
echo.
echo for /f "tokens=1,2 delims==" %%%%a in ^(%CONFIG%^) do ^(
echo   if "%%%%a"=="WALLET" set "WALLET=%%%%b"
echo   if "%%%%a"=="POOL_HOST" set "POOL_HOST=%%%%b"
echo   if "%%%%a"=="POOL_PORT" set "POOL_PORT=%%%%b"
echo   if "%%%%a"=="THREADS" set "THREADS=%%%%b"
echo   if "%%%%a"=="WORKER_NAME" set "WORKER=%%%%b"
echo   if "%%%%a"=="METRICS_PORT" set "METRICS_PORT=%%%%b"
echo ^)
echo.
echo echo.
echo echo   DagTech Miner - dagtech.network
echo echo   Pool: %%POOL_HOST%%:%%POOL_PORT%%
echo echo   Wallet: %%WALLET%%
echo echo   Threads: %%THREADS%%
echo echo.
echo.
echo REM Start dashboard
echo start /min python -m http.server 8881 --bind 127.0.0.1 --directory "%%DASHBOARD%%" 2^>nul
echo echo [DagTech] Dashboard: http://localhost:8881
echo.
echo "%%BIN%%" --wallet %%WALLET%% --pool %%POOL_HOST%% --port %%POOL_PORT%% --threads %%THREADS%% --worker %%WORKER%% --metrics-port %%METRICS_PORT%%
) > "%BIN_DIR%\dagtech-start.bat"

(
echo @echo off
echo taskkill /f /im dagtech-miner.exe 2^>nul ^&^& echo [DagTech] Miner stopped ^|^| echo [DagTech] Miner not running
) > "%BIN_DIR%\dagtech-stop.bat"

REM ---- Add to PATH ----
echo [DagTech] Adding to PATH...
setx PATH "%PATH%;%BIN_DIR%" >nul 2>&1

REM ---- Done ----
echo.
echo   =============================================
echo     Installation Complete!
echo   =============================================
echo.
echo   Quick Start:
echo     dagtech-start.bat    Start mining
echo     dagtech-stop.bat     Stop mining
echo.
echo   Dashboard:
echo     Open http://localhost:8881 while mining
echo.
echo   Config: %CONFIG_FILE%
echo   Logs:   %LOG_DIR%
echo.
echo   DagTech Mining Suite v%DAGTECH_VERSION%
echo   By Dawie Nel / DagTech Ltd
echo   https://dagtech.network
echo.
pause
