#!/usr/bin/env python3
"""DagTech Miner Dashboard Server v3.0
Serves the dashboard UI and provides API endpoints for:
- GET  /api/metrics   — proxied from miner's metrics port
- GET  /api/config    — read current config.env
- POST /api/config    — write config.env
- POST /api/restart   — restart the miner process
- GET  /api/hardware  — detect CPU, GPU, RAM, OS
"""
import http.server, json, os, platform, re, signal, subprocess, sys, urllib.request

DD = os.path.dirname(os.path.abspath(__file__))
MU = "http://127.0.0.1:8880/"
CONFIG_FILE = os.path.join(os.path.expanduser("~"), ".dagtech-miner", "config.env")
BIN_DIR = os.path.join(os.path.expanduser("~"), ".dagtech-miner", "bin")


def read_config():
    """Read config.env into a dict."""
    cfg = {}
    if not os.path.exists(CONFIG_FILE):
        return cfg
    with open(CONFIG_FILE, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                k, v = line.split("=", 1)
                cfg[k.strip()] = v.strip()
    return cfg


def write_config(cfg):
    """Write config dict back to config.env."""
    os.makedirs(os.path.dirname(CONFIG_FILE), exist_ok=True)
    lines = [
        "# DagTech Miner Configuration",
        "# Generated by DagTech Dashboard v3.0",
        f"# https://dagtech.network",
        "",
    ]
    key_order = [
        "WALLET", "POOL_HOST", "POOL_PORT", "MINING_MODE", "THREADS",
        "WORKER_NAME", "POOL_PASSWORD", "LOW_PRIORITY", "METRICS_PORT",
        "GPU_INTENSITY", "GPU_THROTTLE", "CPU_LIMIT",
    ]
    written = set()
    for k in key_order:
        if k in cfg:
            lines.append(f"{k}={cfg[k]}")
            written.add(k)
    for k, v in cfg.items():
        if k not in written:
            lines.append(f"{k}={v}")
    with open(CONFIG_FILE, "w") as f:
        f.write("\n".join(lines) + "\n")


def detect_hardware():
    """Detect CPU, GPU, RAM, and OS info."""
    hw = {"cpu": "", "cores": 0, "arch": "", "gpu": "", "gpu_vram": "", "ram_mb": 0, "os": ""}

    hw["os"] = f"{platform.system()} {platform.release()}"
    hw["arch"] = platform.machine()

    try:
        hw["cores"] = os.cpu_count() or 0
    except Exception:
        pass

    if platform.system() == "Linux":
        try:
            with open("/proc/cpuinfo") as f:
                for line in f:
                    if "model name" in line:
                        hw["cpu"] = line.split(":")[1].strip()
                        break
            with open("/proc/meminfo") as f:
                for line in f:
                    if "MemTotal" in line:
                        hw["ram_mb"] = int(re.findall(r"\d+", line)[0]) // 1024
                        break
        except Exception:
            pass
        try:
            r = subprocess.run(
                ["nvidia-smi", "--query-gpu=name,memory.total", "--format=csv,noheader"],
                capture_output=True, text=True, timeout=5,
            )
            if r.returncode == 0 and r.stdout.strip():
                parts = r.stdout.strip().split(",")
                hw["gpu"] = parts[0].strip()
                hw["gpu_vram"] = parts[1].strip() if len(parts) > 1 else ""
        except Exception:
            pass

    elif platform.system() == "Darwin":
        try:
            r = subprocess.run(["sysctl", "-n", "machdep.cpu.brand_string"], capture_output=True, text=True, timeout=5)
            hw["cpu"] = r.stdout.strip()
            r = subprocess.run(["sysctl", "-n", "hw.memsize"], capture_output=True, text=True, timeout=5)
            hw["ram_mb"] = int(r.stdout.strip()) // (1024 * 1024)
            r = subprocess.run(["system_profiler", "SPHardwareDataType"], capture_output=True, text=True, timeout=10)
            for line in r.stdout.splitlines():
                if "Chip" in line:
                    hw["gpu"] = line.split(":")[1].strip() + " (integrated)"
                    break
        except Exception:
            pass

    elif platform.system() == "Windows":
        try:
            r = subprocess.run(
                ["wmic", "cpu", "get", "Name", "/value"],
                capture_output=True, text=True, timeout=5, shell=True,
            )
            for line in r.stdout.splitlines():
                if "Name=" in line:
                    hw["cpu"] = line.split("=")[1].strip()
                    break
            r = subprocess.run(
                ["wmic", "os", "get", "TotalVisibleMemorySize", "/value"],
                capture_output=True, text=True, timeout=5, shell=True,
            )
            for line in r.stdout.splitlines():
                if "TotalVisibleMemorySize=" in line:
                    hw["ram_mb"] = int(line.split("=")[1].strip()) // 1024
                    break
            r = subprocess.run(
                ["nvidia-smi", "--query-gpu=name,memory.total", "--format=csv,noheader"],
                capture_output=True, text=True, timeout=5,
            )
            if r.returncode == 0 and r.stdout.strip():
                parts = r.stdout.strip().split(",")
                hw["gpu"] = parts[0].strip()
                hw["gpu_vram"] = parts[1].strip() if len(parts) > 1 else ""
        except Exception:
            pass

    return hw


def stop_miner():
    """Stop the miner process."""
    system = platform.system()
    try:
        if system == "Windows":
            subprocess.run(["taskkill", "/f", "/im", "dagtech-miner.exe"], capture_output=True, timeout=5)
            subprocess.run(["taskkill", "/f", "/im", "dagtech-gpu-miner.exe"], capture_output=True, timeout=5)
        else:
            subprocess.run(["pkill", "-f", "dagtech-miner"], capture_output=True, timeout=5)
            subprocess.run(["pkill", "-f", "dagtech-gpu-miner"], capture_output=True, timeout=5)
        return True
    except Exception as e:
        return str(e)


def restart_miner():
    """Stop and restart the miner process."""
    system = platform.system()
    try:
        if system == "Windows":
            subprocess.run(["taskkill", "/f", "/im", "dagtech-miner.exe"], capture_output=True, timeout=5)
            subprocess.run(["taskkill", "/f", "/im", "dagtech-gpu-miner.exe"], capture_output=True, timeout=5)
            start_script = os.path.join(BIN_DIR, "dagtech-start.bat")
            if os.path.exists(start_script):
                subprocess.Popen(["cmd", "/c", "start", "/min", start_script], shell=True)
        else:
            subprocess.run(["pkill", "-f", "dagtech-miner"], capture_output=True, timeout=5)
            subprocess.run(["pkill", "-f", "dagtech-gpu-miner"], capture_output=True, timeout=5)
            start_script = os.path.join(BIN_DIR, "dagtech-start")
            if os.path.exists(start_script):
                subprocess.Popen([start_script], start_new_session=True)
        return True
    except Exception as e:
        return str(e)


class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *a, **k):
        super().__init__(*a, directory=DD, **k)

    def _json_response(self, code, data):
        body = json.dumps(data).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Content-Length", len(body))
        self.end_headers()
        self.wfile.write(body)

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_GET(self):
        if self.path == "/api/metrics":
            try:
                with urllib.request.urlopen(
                    urllib.request.Request(MU, headers={"Accept": "application/json"}),
                    timeout=3,
                ) as r:
                    d = r.read()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.send_header("Content-Length", len(d))
                self.end_headers()
                self.wfile.write(d)
            except Exception as e:
                self._json_response(502, {"error": str(e)})

        elif self.path == "/api/config":
            try:
                cfg = read_config()
                self._json_response(200, cfg)
            except Exception as e:
                self._json_response(500, {"error": str(e)})

        elif self.path == "/api/hardware":
            try:
                hw = detect_hardware()
                self._json_response(200, hw)
            except Exception as e:
                self._json_response(500, {"error": str(e)})

        else:
            super().do_GET()

    def do_POST(self):
        if self.path == "/api/config":
            try:
                length = int(self.headers.get("Content-Length", 0))
                body = self.rfile.read(length)
                new_cfg = json.loads(body)
                existing = read_config()
                existing.update(new_cfg)
                write_config(existing)
                self._json_response(200, {"status": "saved", "config": existing})
            except Exception as e:
                self._json_response(500, {"error": str(e)})

        elif self.path == "/api/restart":
            try:
                length = int(self.headers.get("Content-Length", 0))
                body = json.loads(self.rfile.read(length)) if length > 0 else {}
                action = body.get("action", "restart")
                if action == "stop":
                    stop_miner()
                    self._json_response(200, {"status": "stopped"})
                else:
                    result = restart_miner()
                    if result is True:
                        self._json_response(200, {"status": "restarting"})
                    else:
                        self._json_response(500, {"error": result})
            except Exception as e:
                self._json_response(500, {"error": str(e)})

        else:
            self._json_response(404, {"error": "not found"})

    def log_message(self, *a):
        pass


if __name__ == "__main__":
    mp = int(sys.argv[2]) if len(sys.argv) > 2 else 8880
    MU = f"http://127.0.0.1:{mp}/"
    p = int(sys.argv[1]) if len(sys.argv) > 1 else 8881
    print(f"[DASH] DagTech Dashboard v3.0 on :{p}, metrics from :{mp}")
    print(f"[DASH] Config: {CONFIG_FILE}")
    print(f"[DASH] Hardware detection: {platform.system()} {platform.machine()}")
    http.server.HTTPServer(("0.0.0.0", p), Handler).serve_forever()
