@echo off
setlocal enabledelayedexpansion
set "CONFIG=%APPDATA%\DagTech Miner\config.env"
set "INSTALL_DIR=%APPDATA%\DagTech Miner"

echo.
echo   =============================================
echo     DagTech Miner - Configuration Wizard
echo     dagtech.network
echo   =============================================
echo.

REM ---- Check for existing config ----
if exist "%CONFIG%" (
    echo [DagTech] Existing config found.
    set /p "RECONFIG=  Reconfigure? [y/N]: "
    if /i not "!RECONFIG!"=="y" (
        echo [DagTech] Keeping existing configuration.
        pause
        exit /b 0
    )
)

REM ---- Wallet ----
:wallet_prompt
echo.
set /p "WALLET=  Enter wallet address (0x...): "
powershell -Command ^
  "$w = '%WALLET%'; " ^
  "if ($w -match '^0x[0-9a-fA-F]{40}$') { exit 0 } " ^
  "elseif ($w -notmatch '^0x') { Write-Host '[DagTech] Address must start with 0x'; exit 1 } " ^
  "elseif ($w.Length -lt 42) { Write-Host \"[DagTech] Address too short ($($w.Length) chars, need 42)\"; exit 1 } " ^
  "elseif ($w.Length -gt 42) { Write-Host \"[DagTech] Address too long ($($w.Length) chars, need 42)\"; exit 1 } " ^
  "else { Write-Host '[DagTech] Invalid characters. Use only 0-9 and a-f after 0x.'; exit 1 }"
if errorlevel 1 goto :wallet_prompt

REM ---- GPU check ----
set "GPU_AVAILABLE=0"
nvidia-smi >nul 2>&1
if not errorlevel 1 (
    set "GPU_AVAILABLE=1"
    echo.
    echo [DagTech] NVIDIA GPU detected
    for /f "tokens=*" %%a in ('nvidia-smi --query-gpu^=name --format^=csv^,noheader 2^>nul') do echo   GPU: %%a
)

REM ---- Mining mode ----
echo.
echo   Mining mode:
if "%GPU_AVAILABLE%"=="1" (
    echo     1^) CPU only
    echo     2^) GPU only
    echo     3^) CPU + GPU [recommended]
    echo.
    set /p "MODE_CHOICE=  Choice [1-3]: "
) else (
    echo     1^) CPU only
    set "MODE_CHOICE=1"
)
set "MINING_MODE=cpu"
if "%MODE_CHOICE%"=="2" set "MINING_MODE=gpu"
if "%MODE_CHOICE%"=="3" set "MINING_MODE=both"

REM ---- Threads ----
for /f "tokens=2 delims==" %%a in ('wmic cpu get NumberOfLogicalProcessors /value 2^>nul ^| find "="') do set "CPU_CORES=%%a"
set /a "DEFAULT_THREADS=%CPU_CORES% / 2"
if %DEFAULT_THREADS% LSS 1 set "DEFAULT_THREADS=1"
echo.
set /p "THREADS=  CPU threads (1-%CPU_CORES%, default %DEFAULT_THREADS%): "
if "%THREADS%"=="" set "THREADS=%DEFAULT_THREADS%"

REM ---- Pool ----
echo.
set "POOL_HOST=excalibur.dagtech.network"
set "POOL_PORT=3335"
set /p "POOL_INPUT=  Pool address (default: %POOL_HOST%): "
if not "%POOL_INPUT%"=="" set "POOL_HOST=%POOL_INPUT%"
set /p "PORT_INPUT=  Pool port (default: %POOL_PORT%): "
if not "%PORT_INPUT%"=="" set "POOL_PORT=%PORT_INPUT%"

REM ---- Worker ----
echo.
set "WORKER=dagtech"
set /p "WORKER_INPUT=  Worker name (default: dagtech): "
if not "%WORKER_INPUT%"=="" set "WORKER=%WORKER_INPUT%"

REM ---- Save ----
(
echo # DagTech Miner Configuration
echo # Generated by DagTech Installer v3.0.0
echo WALLET=%WALLET%
echo POOL_HOST=%POOL_HOST%
echo POOL_PORT=%POOL_PORT%
echo MINING_MODE=%MINING_MODE%
echo THREADS=%THREADS%
echo WORKER_NAME=%WORKER%
echo METRICS_PORT=8880
) > "%CONFIG%"

echo.
echo [DagTech] Configuration saved to %CONFIG%
echo.
pause
